server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://rm-cn-nwy3if5e1002nczo.rwlb.rds.aliyuncs.com:3306/cc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ywt
    password: Pg24011011
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456